name: manuals
run-name: ${{ gitea.actor }} is building lab/manuals image.

on:
  push: 
    branches: [deploy]

jobs:
  build-oci:
    runs-on: [system]
    steps:

    - name: Check out repository code
      uses: https://git.lab/actions/checkout@v4

    - name: Dump environment variables
      run: env
    
    - name: Login to Gitea Docker Registry
      uses: https://git.lab/docker/login-action@v3
      with:
        registry: git.lab
        username: ${{ secrets.GITEADOCKER_USERNAME }}
        password: ${{ secrets.GITEADOCKER_TOKEN }}

    - name: Build system_manual image
      run: ./do cicd
    
    # Assumed that /opt/services is pre-created and owned by cicd.
    - name: Deploy system_manual image
      run: |
        ssh -p 2222 -o StrictHostKeyChecking=no cicd@www.lab /bin/sh <<EOF
        cd /opt/services
        if [ ! -e system_services ]; then
          git clone https://git.lab/lab/system_services.git
        fi
        cd system_services
        git pull
        docker compose pull && docker compose up -d
        # docker compose up --force-recreate --build -d
        # docker image prune -f
        EOF
        ""